[package]
name = "vatsim-api"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0 OR MIT"
description = "Rust types, async client, and mock server for various VATSIM APIs."
repository = "https://github.com/MorpheusXAUT/vatsim-api"
homepage = "https://github.com/MorpheusXAUT/vatsim-api"
keywords = ["vatsim", "flight-simulation", "aviation", "api"]
categories = ["api-bindings"]
readme = "README.md"

[features]
default = ["serde"]
client = ["serde", "dep:reqwest", "dep:serde_json", "dep:thiserror", "dep:tokio"]
mock = ["serde", "dep:axum", "dep:rust-embed", "dep:serde_json", "dep:thiserror", "dep:tokio", "dep:tower-http"]
serde = ["dep:serde"]
tracing = ["axum?/tracing", "tower-http?/trace", "dep:tracing"]

[dependencies]
axum = { version = "0.8", optional = true }
reqwest = { version = "0.13", features = ["json"], optional = true }
rust-embed = { version = "8", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
thiserror = { version = "2", optional = true }
tokio = { version = "1", features = ["rt", "time", "sync"], optional = true }
tower-http = { version = "0.6", features = ["fs", "cors"], optional = true }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
